export default {
  index: "Overview",
  discipline: "Discipline & Suspension",
  charter: "Charter School Rights",
  sped: "Special Education & IEPs",
  records: "Records & Information",
  transportation: "Transportation Rights",
  homelessness: "Homelessness & Housing",
  "foster-care": "Foster Care & Transitions",
  bullying: "Bullying & Discrimination",
  "parent-involvement": "Parent Involvement & PTA",
  gifted: "Gifted Education",
  prek3: "Pre-K3 Programs",
  testing: "Testing & Accountability",
  "sports-arts": "Sports, Music & Arts",
  stem: "STEM & Technology",
  "brain-science": "Brain Science & Best Practices",
};
